server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.243.242.192:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: hmdp
    password: LmXrmbXn3Ey2Jr2c
  redis:
    host: 47.243.242.192
    port: 36790
    database: 0
    password: redisAngelXin
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.241.128:8881
#        - 192.168.241.128:8882
#        - 192.168.241.128:8883
    lettuce:
      pool:
        max-active: 20   #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 10       #连接池中的最小空闲连接
        time-between-eviction-runs: 10s #指定两次空闲连接回收（eviction）的时间间隔
        max-wait: 15   #最大阻塞等待时间（负数表示没有限制）
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

